Cleaned up the output and added the option to run the 'set' command after 'choose-remaining' completes

diff --git a/gnome-catgen b/gnome-catgen
--- a/gnome-catgen
+++ b/gnome-catgen
@@ -16,7 +16,7 @@ function getapps() {
     done
 }
 
-function getremaining() {
+function getr() {
     # Fail if the config directory doesn't exist
     if [ ! -d "$CATPATH" ]; then
         echo "The configuration folder '$CATPATH' is either read-only or it doesn't exist"
@@ -50,6 +50,68 @@ function getremaining() {
     [[ -f "${TMPFILE}.2" ]] && rm "${TMPFILE}.2"
 }
 
+function set() {
+    # Fail if the config directory doesn't exist
+    if [ ! -d "$CATPATH" ]; then
+        echo "The configuration folder '$CATPATH' is either read-only or it doesn't exist"
+        exit 1
+    fi
+
+    # Set the category types and reset any current app data
+    echo -e "Setting configured folder categories in dconf...\n"
+    CATEGORIES=$(ls -1 "${CATPATH}" | grep -e ".category$" | sed 's/.category//g' | sed -e ':a;N;$!ba;'"s/\n/', '/g;s/^/['/g;s/$/']/g")
+    gsettings set org.gnome.desktop.app-folders folder-children "$CATEGORIES"
+
+    echo "Clearing old category data before populating"
+    dconf reset -f /org/gnome/desktop/app-folders/folders/
+
+    # Add the app data for each category and output an error if none is defined
+    gsettings get org.gnome.desktop.app-folders folder-children | sed "s/\[//g;s/\]//g;s/^'//g;s/'$//g;s/',\ *'/\n/g" | while read -r cat; do
+        echo -e "\nAdding category: ${cat}"
+        echo -n > "$TMPFILE"
+        cat "${CATPATH}/${cat}.category" | while read -r program; do
+            if [ $(echo "$program" | grep -v -e "[^[\ ]*#") ]; then
+                if [ -f "/usr/share/applications/${program}" ] || [ -f "${HOME}/.local/share/applications/${program}" ]; then
+                    echo "$program" >> "$TMPFILE"
+                fi
+            fi
+        done
+        if [ ! $(cat "$TMPFILE" | wc -l) = 0 ]; then
+            CATEGORY=$(sed -e ':a;N;$!ba;'"s/\n/', '/g" "$TMPFILE" | sed "s/^[\"',\ ]*/['/g;s/[\"',\ ]*$/']/g")
+            gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/${cat}/ apps "$CATEGORY"
+        fi
+    done
+    [[ -f "$TMPFILE" ]] && rm "$TMPFILE"
+    echo -e "\nDone!"
+}
+
+function chooser() {
+    # Fail if the config directory isn't available and writable
+    if [ ! -w "$CATPATH" ]; then
+        echo "The configuration folder '$CATPATH' is either read-only or it doesn't exist"
+        exit 1
+    fi
+
+    echo -e "Type the desired category name for each program then hit enter, blank to skip and ctrl-c to quit.\n"
+    getr | while read -r app; do
+        echo -n "$app: "
+        read CAT </dev/tty
+        [[ ! -z "$CAT" ]] && echo "$app" >> "${CATPATH}/${CAT}.category" || echo "Skipping ${app}..."
+    done
+
+    while [ 0 ]; do
+        echo -en "\nCreate and populate configured folder categories in dconf? [y/n]: "
+        read SET
+        if [ "$SET" = "Y" ] || [ "$SET" = "y" ]; then
+            set; break
+        elif [ "$SET" = "N" ] || [ "$SET" = "n" ]; then
+            break
+        else
+            echo "Error: Invalid option"
+        fi
+    done
+}
+
 function help() {
     echo -e "GNOME CATGEN (Folder Category Generator for Gnome 3.12)\n"
     echo -e "To use, create files named after a folder category and ending with '.category' in '${CATPATH}/' (eg: '${CATPATH}/Games.category'), then inside each, put the filename of the .desktop file associated with an application you'd like to include on each line (eg: 'gvim.desktop'). Lines starting with # or that include .desktop files that don't exist in /usr/share/applications or ~/.local/share/applications will be ignored. When you're ready, run '$0 set' to generate your folders.\n"
@@ -59,7 +121,7 @@ function help() {
     echo -e "\t${APPNAME} get-remaining 'or' getr | list the apps without a folder category in the config"
     echo -e "\t${APPNAME} get | list all of the above with labels\n"
     echo -e "\t${APPNAME} choose-remaining 'or' chooser | choose folder categories for apps currently without one in the config"
-    echo -e "\t${APPNAME} set | create and populate configured folder categories dconf"
+    echo -e "\t${APPNAME} set | create and populate configured folder categories in dconf"
     echo -e "\t${APPNAME} clear | remove all folder categories and their contents from dconf (doesn't touch config)\n"
     echo -e "\t${APPNAME} help 'or' -h 'or' --help | display this help"
 }
@@ -67,65 +129,20 @@ function help() {
 [[ -d "$CATPATH" ]] || install -d "$CATPATH"
 
 if [ -n "$1" ]; then
-    if [ "$1" = "get" ]; then
-        echo -n "Folders: "
-        getfolders
-        echo
-        getapps
-        echo "Programs in Activities without folders:"
-        getremaining
-    elif [ "$1" = "get-folders" ]; then
+    if [ "$1" = "get-folders" ]; then
         getfolders
     elif [ "$1" = "get-apps" ]; then
         getapps
     elif [ "$1" = "get-remaining" ] || [ "$1" = "getr" ]; then
-        getremaining
-    elif [ "$1" = "set" ]; then
-        # Fail if the config directory doesn't exist
-        if [ ! -d "$CATPATH" ]; then
-            echo "The configuration folder '$CATPATH' is either read-only or it doesn't exist"
-            exit 1
-        fi
-
-        # Set the category types and reset any current app data
-        echo "Setting new category list"
-        CATEGORIES=$(ls -1 "${CATPATH}" | grep -e ".category$" | sed 's/.category//g' | sed -e ':a;N;$!ba;'"s/\n/', '/g;s/^/['/g;s/$/']/g")
-        gsettings set org.gnome.desktop.app-folders folder-children "$CATEGORIES"
-
-        echo "Clearing old category data before populating"
-        dconf reset -f /org/gnome/desktop/app-folders/folders/
-
-        # Add the app data for each category and output an error if none is defined
-        gsettings get org.gnome.desktop.app-folders folder-children | sed "s/\[//g;s/\]//g;s/^'//g;s/'$//g;s/',\ *'/\n/g" | while read -r cat; do
-            echo -e "\nAdding category: ${cat}"
-            echo -n > "$TMPFILE"
-            cat "${CATPATH}/${cat}.category" | while read -r program; do
-                if [ $(echo "$program" | grep -v -e "[^[\ ]*#") ]; then
-                    if [ -f "/usr/share/applications/${program}" ] || [ -f "${HOME}/.local/share/applications/${program}" ]; then
-                        echo "$program" >> "$TMPFILE"
-                    fi
-                fi
-            done
-            if [ ! $(cat "$TMPFILE" | wc -l) = 0 ]; then
-                CATEGORY=$(sed -e ':a;N;$!ba;'"s/\n/', '/g" "$TMPFILE" | sed "s/^[\"',\ ]*/['/g;s/[\"',\ ]*$/']/g")
-                gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/${cat}/ apps "$CATEGORY"
-            fi
-        done
-        [[ -f "$TMPFILE" ]] && rm "$TMPFILE"
-        echo -e "\nDone!"
+        getr
+    elif [ "$1" = "get" ]; then
+        echo -n "Folders: "; getfolders
+        echo; getapps
+        echo "Programs in Activities without folders:"; getr
     elif [ "$1" = "choose-remaining" ] || [ "$1" = "chooser" ]; then
-        # Fail if the config directory isn't available and writable
-        if [ ! -w "$CATPATH" ]; then
-            echo "The configuration folder '$CATPATH' is either read-only or it doesn't exist"
-            exit 1
-        fi
-
-        echo -e "Type the desired category name for each program then hit enter, blank to skip and ctrl-c to quit.\n"
-        getremaining | while read -r app; do
-            echo "$app: "
-            read CAT </dev/tty
-            [[ ! -z "$CAT" ]] && echo "$app" >> "${CATPATH}/${CAT}.category" || echo "Skipping ${app}..."
-        done
+        chooser
+    elif [ "$1" = "set" ]; then
+        set
     elif [ "$1" = "clear" ]; then
         # Set the category types and reset any current app data
         gsettings set org.gnome.desktop.app-folders folder-children "[]"
